DROP DATABASE IF EXISTS rustydb;
CREATE DATABASE rustydb owner postgres ENCODING = 'UTF-8';
DROP SEQUENCE IF EXISTS item_id_seq;
DROP SEQUENCE IF EXISTS order_id_seq;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Tables;
DROP TABLE IF EXISTS Orders;